# Generated by Django 5.1.7 on 2025-04-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Título')),
                ('cu', models.CharField(max_length=15, unique=True, verbose_name='Código único')),
                ('author', models.ManyToManyField(to='authors.author')),
            ],
            options={
                'verbose_name': ('Book',),
                'verbose_name_plural': 'Books',
            },
        ),
    ]
